services:
  postgres:
    image: postgres:15-alpine
    container_name: stella_db
    restart: always
    environment:
      POSTGRES_USER: stella_user
      POSTGRES_PASSWORD: stella_password
      POSTGRES_DB: stella_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
